-- Create LOCATION table
CREATE TABLE LOCATION (
  Location_ID INT PRIMARY KEY,
  City VARCHAR(50)
);

-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
  Department_Id INT PRIMARY KEY,
  Name VARCHAR(50),
  Location_Id INT,
  FOREIGN KEY (Location_Id) REFERENCES LOCATION(Location_ID)
);

-- Create JOB table
CREATE TABLE JOB (
  Job_ID INT PRIMARY KEY,
  Designation VARCHAR(50)
);

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INT PRIMARY KEY,
  LAST_NAME VARCHAR(20),
  FIRST_NAME VARCHAR(20),
  MIDDLE_NAME CHAR(1),
  JOB_ID INT,
  MANAGER_ID INT,
  HIRE_DATE DATE,
  SALARY INT,
  COMM INT,
  DEPARTMENT_ID INT,
  FOREIGN KEY (JOB_ID) REFERENCES JOB(Job_ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(Department_Id)
);
